INSERT INTO artists (name) VALUES ("Alice in Chains");
INSERT INTO artists (name) VALUES ("Neil Young");
INSERT INTO artists (name) VALUES ("Led Zeppelin");
INSERT INTO artists (name) VALUES ("Metallica");
INSERT INTO artists (name) VALUES ("Bruce Springsteen");
INSERT INTO artists (name) VALUES ("Duster");
INSERT INTO artists (name) VALUES ("My Bloody Valentine");
INSERT INTO artists (name) VALUES ("The Cure");
INSERT INTO artists (name) VALUES ("The Smiths");
INSERT INTO artists (name) VALUES ("Foo Fighters");